import jsPDF from 'jspdf';

export function generatePDFReport(instances, formatTimestamp) {
    // Generate comprehensive PDF report
    const reportDate = new Date().toLocaleString();
    const userName = localStorage.getItem('user') || 'User';

    // Group instances by provider
    const byProvider = {};
    instances.forEach(inst => {
        const provider = inst.provider || 'Unknown';
        if (!byProvider[provider]) byProvider[provider] = [];
        byProvider[provider].push(inst);
    });

    // Calculate summary statistics
    const totalInstances = instances.length;
    const runningInstances = instances.filter(i => (i.status || '').toLowerCase() === 'running').length;
    const stoppedInstances = instances.filter(i => (i.status || '').toLowerCase() === 'stopped').length;
    const optimizedInstances = instances.filter(i => {
        const providerLower = (i.provider || '').toLowerCase();
        if (providerLower === 'aws' && i.compute_optimizer_finding) {
            return i.compute_optimizer_finding === 'Optimized';
        }
        return (i.optimizationStatus || '').toUpperCase() === 'OPTIMAL';
    }).length;
    const needsAttentionInstances = instances.filter(i => {
        const providerLower = (i.provider || '').toLowerCase();
        if (providerLower === 'aws' && i.compute_optimizer_finding) {
            return ['Overprovisioned', 'Underprovisioned'].includes(i.compute_optimizer_finding);
        }
        return ['OVERSIZED', 'UNDERSIZED', 'OVERUTILIZED', 'UNDERUTILIZED'].includes((i.optimizationStatus || '').toUpperCase());
    }).length;
    const totalSavingsCalc = instances.reduce((sum, i) => sum + (i.potential_monthly_savings || 0), 0);

    // Create PDF
    const doc = new jsPDF();
    let yPos = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;

    // Helper function to check if we need a new page
    const checkPageBreak = (requiredSpace = 10) => {
        if (yPos + requiredSpace > pageHeight - 20) {
            doc.addPage();
            yPos = 20;
            return true;
        }
        return false;
    };

    // Header with logo placeholder and title
    doc.setFillColor(0, 120, 212); // Azure blue
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('CLOUD OPTIMIZATION REPORT', pageWidth / 2, 20, { align: 'center' });
    doc.setFontSize(12);
    doc.text('CloudOptix Platform', pageWidth / 2, 30, { align: 'center' });

    // Reset text color
    doc.setTextColor(0, 0, 0);
    yPos = 50;

    // Report metadata
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${reportDate}`, margin, yPos);
    yPos += 5;
    doc.text(`Generated By: ${userName}`, margin, yPos);
    yPos += 15;

    // Executive Summary Section
    doc.setFillColor(240, 240, 240);
    doc.rect(margin, yPos - 5, maxWidth, 8, 'F');
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('EXECUTIVE SUMMARY', margin + 2, yPos);
    yPos += 12;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const summaryData = [
        ['Total Instances:', totalInstances.toString()],
        ['Running Instances:', runningInstances.toString()],
        ['Stopped Instances:', stoppedInstances.toString()],
        ['Optimized Instances:', optimizedInstances.toString()],
        ['Needs Attention:', needsAttentionInstances.toString()],
        ['Total Potential Savings:', `$${totalSavingsCalc.toFixed(2)}/month`]
    ];

    summaryData.forEach(([label, value]) => {
        checkPageBreak();
        doc.setFont('helvetica', 'bold');
        doc.text(label, margin + 5, yPos);
        doc.setFont('helvetica', 'normal');
        doc.text(value, margin + 80, yPos);
        yPos += 6;
    });

    yPos += 10;

    // Instances by Provider Section
    Object.keys(byProvider).sort().forEach(provider => {
        const providerInstances = byProvider[provider];
        const providerSavings = providerInstances.reduce((sum, i) => sum + (i.potential_monthly_savings || 0), 0);

        checkPageBreak(20);

        // Provider header with color coding
        let providerColor = [0, 120, 212]; // Default blue
        if (provider === 'AWS') providerColor = [255, 153, 0]; // Orange
        else if (provider === 'Azure') providerColor = [0, 120, 212]; // Blue
        else if (provider === 'GCP') providerColor = [52, 168, 83]; // Green

        doc.setFillColor(...providerColor);
        doc.rect(margin, yPos - 5, maxWidth, 8, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(`${provider.toUpperCase()} - ${providerInstances.length} Instances (Savings: $${providerSavings.toFixed(2)}/month)`, margin + 2, yPos);
        doc.setTextColor(0, 0, 0);
        yPos += 12;

        // Instance details
        providerInstances.forEach((inst, idx) => {
            checkPageBreak(35);

            const cpuAvg = inst.cpu_avg != null ? inst.cpu_avg.toFixed(1) : (inst.avgCpuUtilization != null ? inst.avgCpuUtilization.toFixed(1) : 'N/A');
            const memAvg = inst.memory_avg != null ? inst.memory_avg.toFixed(1) : (inst.avgMemoryUtilization != null ? inst.avgMemoryUtilization.toFixed(1) : 'N/A');
            const savings = inst.potential_monthly_savings != null ? inst.potential_monthly_savings.toFixed(2) : '0.00';

            // Determine optimization status
            let optStatus = 'Unknown';
            if (inst.provider === 'AWS' && inst.compute_optimizer_finding) {
                optStatus = inst.compute_optimizer_finding;
            } else if (inst.recommendation) {
                optStatus = inst.recommendation;
            } else if (inst.optimizationStatus) {
                optStatus = inst.optimizationStatus;
            }

            // Instance name
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.text(`${idx + 1}. ${inst.name || 'Unnamed Instance'}`, margin + 5, yPos);
            yPos += 5;

            // Instance details
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            const details = [
                `Instance ID: ${inst.resourceId || 'N/A'}`,
                `Type: ${inst.resourceType || 'N/A'}  |  Region: ${inst.region || 'N/A'}  |  Status: ${inst.status || 'Unknown'}`,
                `OS: ${inst.os_type || 'Unknown'}  |  CPU: ${cpuAvg}${cpuAvg !== 'N/A' ? '%' : ''}  |  Memory: ${memAvg}${memAvg !== 'N/A' ? '%' : ''}`,
                `Optimization: ${optStatus}  |  Savings: $${savings}/month`
            ];

            if (inst.recommended_instance_type) {
                details.push(`Recommended: ${inst.recommended_instance_type}`);
            }

            details.forEach(detail => {
                checkPageBreak();
                doc.text(detail, margin + 8, yPos);
                yPos += 4;
            });

            yPos += 3;
        });

        yPos += 5;
    });

    // Recommendations Summary Section
    checkPageBreak(20);
    doc.setFillColor(240, 240, 240);
    doc.rect(margin, yPos - 5, maxWidth, 8, 'F');
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('RECOMMENDATIONS SUMMARY', margin + 2, yPos);
    yPos += 12;

    const overprovisioned = instances.filter(i => {
        const providerLower = (i.provider || '').toLowerCase();
        if (providerLower === 'aws' && i.compute_optimizer_finding) {
            return i.compute_optimizer_finding === 'Overprovisioned';
        }
        return ['OVERSIZED', 'OVERUTILIZED'].includes((i.optimizationStatus || '').toUpperCase());
    });

    const underprovisioned = instances.filter(i => {
        const providerLower = (i.provider || '').toLowerCase();
        if (providerLower === 'aws' && i.compute_optimizer_finding) {
            return i.compute_optimizer_finding === 'Underprovisioned';
        }
        return ['UNDERSIZED', 'UNDERUTILIZED'].includes((i.optimizationStatus || '').toUpperCase());
    });

    if (overprovisioned.length > 0) {
        checkPageBreak(15);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(`OVER-PROVISIONED INSTANCES (${overprovisioned.length})`, margin + 5, yPos);
        yPos += 5;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.text('These instances can be downsized to save costs:', margin + 5, yPos);
        yPos += 6;

        overprovisioned.forEach((inst, idx) => {
            checkPageBreak();
            const savings = inst.potential_monthly_savings != null ? inst.potential_monthly_savings.toFixed(2) : '0.00';
            doc.setFontSize(8);
            doc.text(`${idx + 1}. ${inst.name} (${inst.resourceType}) - Save $${savings}/month`, margin + 8, yPos);
            yPos += 4;
            if (inst.recommended_instance_type) {
                doc.text(`   -> Recommended: ${inst.recommended_instance_type}`, margin + 8, yPos);
                yPos += 4;
            }
        });
        yPos += 5;
    }

    if (underprovisioned.length > 0) {
        checkPageBreak(15);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(`UNDER-PROVISIONED INSTANCES (${underprovisioned.length})`, margin + 5, yPos);
        yPos += 5;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.text('These instances need more resources:', margin + 5, yPos);
        yPos += 6;

        underprovisioned.forEach((inst, idx) => {
            checkPageBreak();
            doc.setFontSize(8);
            doc.text(`${idx + 1}. ${inst.name} (${inst.resourceType})`, margin + 8, yPos);
            yPos += 4;
            if (inst.recommended_instance_type) {
                doc.text(`   -> Recommended: ${inst.recommended_instance_type}`, margin + 8, yPos);
                yPos += 4;
            }
        });
        yPos += 5;
    }

    if (optimizedInstances > 0) {
        checkPageBreak(10);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(`OPTIMIZED INSTANCES (${optimizedInstances})`, margin + 5, yPos);
        yPos += 5;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.text('These instances are well-sized and require no changes.', margin + 5, yPos);
        yPos += 10;
    }

    // Report Notes Section
    checkPageBreak(30);
    doc.setFillColor(240, 240, 240);
    doc.rect(margin, yPos - 5, maxWidth, 8, 'F');
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('REPORT NOTES', margin + 2, yPos);
    yPos += 12;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    const notes = [
        '• This report is generated based on current instance metrics and optimization data.',
        '• Savings calculations are estimates based on current pricing and usage patterns.',
        '• Always test changes in a non-production environment first.',
        '• Review recommendations with your team before implementing changes.',
        '• For AWS instances, data is sourced from AWS Compute Optimizer when available.',
        '• For other instances, ML-based recommendations are provided.'
    ];

    notes.forEach(note => {
        checkPageBreak();
        const lines = doc.splitTextToSize(note, maxWidth - 10);
        lines.forEach(line => {
            doc.text(line, margin + 5, yPos);
            yPos += 4;
        });
    });

    // Footer
    yPos += 10;
    checkPageBreak(15);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Generated by CloudOptix - Cloud Cost Optimization Platform', margin + 5, yPos);
    yPos += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(`Report ID: ${Date.now()}`, margin + 5, yPos);

    // Add page numbers to all pages
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, pageHeight - 10);
    }

    // Save the PDF
    doc.save(`CloudOptix_Report_${new Date().toISOString().split('T')[0]}.pdf`);

    // Show success message
    alert('PDF report generated successfully! Check your downloads folder.');
}
